### ISSUE TITLE
Приложения ВКредит+

### ISSUE THREAD

**Issue by rakhimian** [FreshApiHub/fresh_api#18]
- [x] Придумать фичи приложения
- [x] Сделать на основе API ВТБ - Управление продуктами кредитной организации

> 1. Завтра до конца дня направим учетные записи и инструкцию как вызывать API.
> 2. Тоже до конца завтрашнего дня предоставим.

[Памятка_доступы.docx](https://github.com/FreshApiHub/fresh_api/files/12860082/_.docx)

**Comment by fishimve** [comment]
**Мини-приложение ВКредит+

Постановка задачи проектирования**

**Comment by fishimve** [comment]
Задание готово дать дизайнерам
